### PR TITLE
Add customizable DHCP hostname

### PR DESCRIPTION
**Pull request by lutzky**
This requires explicitly setting the wifi mode to `WIFI_STA`, but that seems to match the intention anyway.

### CODE REVIEW

**Comment by HON95** [comment]
Sorry for the delay, I'll merge it once I get the time to test it. And yes, setting `WIFI_STA` was on my TODO-list once I noticed my devices were emitting their own WLANs if you don't.

**Comment by lutzky** [comment]
Thanks. FWIW I'm using it live and it works nicely, and you might be able to test it easily - depending on your router (specifically its DNS and DHCP servers), you should be able to ping the hostname you selected (possibly with the suffix `.lan`) right after it connects.

**Comment by dfredell** [comment]
Thanks for posting this MR. This is my first time working with an ESP8266 Mini D1, and this branch's DHCP change is great. I think it is much better to have a DNS name in prometheus instead of an IP 

image

**Comment by HON95** [comment]
Thanks for contributing!

**Pull request merged**
